---
name: Schedule - Keepalive

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/scheduled-keepalive.yaml"

jobs:
  keepalive:
    name: Keep scheduled GitHub workflows alive
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        id: generate-token
        with:
          app_id: "${{ secrets.BOT_APP_ID }}"
          private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout main branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Keep scheduled GitHub workflows alive
        uses: gautamkrishnar/keepalive-workflow@v1
        with:
          gh_token: ${{ steps.generate-token.outputs.token }}
